workerPoolSpecs:
    machineSpec:
        machineType: c2-standard-4
    replicaCount: 1
    containerSpec:
        imageUri: europe-docker.pkg.dev/dtu-mlops-447711/default-container-repository/train@sha256:24dfd4485ec5802c3cf6e4416e13f36acd09c167d2ca2777cdf581accc82b779
        env:
        - name: WANDB_API_KEY
          value: ${WANDB_API_KEY}
