workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-docker.pkg.dev/dtu-mlops-447711/default-container-repository/train:${TAG}
        env:
        - name: WANDB_API_KEY
          value: "${{ secrets.WANDB_API_KEY }}"

