# vertex_ai_config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-4
        acceleratorType: NVIDIA_TESLA_P4 # NVIDIA_TESLA_V100
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: europe-docker.pkg.dev/dtu-mlops-447711/default-container-repository/train:latest