site_name: dtu_mlops_project
site_author: s233489@student.dtu.dk jonnil@dtu.dk s091969@student.dtu.dk s233480@student.dtu.dk
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
