name: Check code with Ruff

on:
  pull_request:
   branches:
     - main
  workflow_dispatch:
    
jobs:
  check:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install ruff
          pip list

      - name: Ruff check
        run: |
          ruff check src/dtu_mlops_project/
          echo "Ruff check completed."
