name: Check, format and fix the code with Ruff

on:
  pull_request:
   branches:
     - main
  workflow_dispatch:
    
jobs:
  check:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install ruff
          pip list

      - name: Ruff check
        run: |
          ruff check src/dtu_mlops_project/ --fix
          echo "Ruff check completed."

      - name: Ruff format
        run: |
          ruff format src/dtu_mlops_project/
          echo "Code formatting with Ruff is complete."

      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/DTU-MLOPS-12/dtu_mlops_project.git
          git add src/dtu_mlops_project/
          git commit -m "Apply Ruff fixes and formatting"
          git push origin HEAD:${{ github.head_ref }}
