name: Check code formatting and style with Ruff and MyPy

on:
  pull_request:
   branches:
     - main
  workflow_dispatch:
    
jobs:
  format:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install ruff
          pip list

      - name: Ruff check and continue
        run: |
          ruff check src/dtu_mlops_project/ || true
          echo "Ruff check completed."

      - name: Mypy type check and continue
        run: | 
          mypy src/dtu_mlops_project/ || true
          echo "Mypy type check completed."
