name: Data Version Control Workflow with DVC

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dvc'
      - '.dvc/**'
  workflow_dispatch:

jobs:
  detect-dvc-change:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Detect DVC changes
        run: echo "change detected"
        
      - name: Extract commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
