name: Fix and format code with Ruff

on:
  workflow_dispatch:
    
jobs:
  format:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install ruff
          pip list

      - name: Ruff format
        run: |
          ruff check src/dtu_mlops_project/ --select I --fix
          ruff format src/dtu_mlops_project/
          echo "Code formatting with Ruff is complete."



