name: Build docker images and push to Google Artifact Registry

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"

env:
  LOCATION: europe
  REPO: default-container-repository
  TAG: latest # ${{ github.event.release.tag_name }}
  PROJECT_ID: dtu-mlops-447711
  GAR_LOCATION: europe-docker.pkg.dev/dtu-mlops-447711/default-container-repository/

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Setup GCP SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker authentication
        run: |
          gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev --quiet

      - name: Build images
        run: |
          docker build -f dockerfiles/api.dockerfile . -t ${{ env.GAR_LOCATION }}api:${{ env.TAG }}
          docker build -f dockerfiles/data.dockerfile . -t ${{ env.GAR_LOCATION }}data:${{ env.TAG }}
          docker build -f dockerfiles/train.dockerfile . -t ${{ env.GAR_LOCATION }}train:${{ env.TAG }}

      - name: Upload to Artifact Registry
        run: |
          docker push ${{ env.GAR_LOCATION }}api:${{ env.TAG }}
          docker push ${{ env.GAR_LOCATION }}data:${{ env.TAG }}
          docker push ${{ env.GAR_LOCATION }}train:${{ env.TAG }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app --image ${{ env.GAR_LOCATION }}api:${{ env.TAG }} --platform managed --region europe-west4 --allow-unauthenticated

