name: Build docker images and push to Google Artifact Registry

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"

env:
  LOCATION: europe
  REPO: default-container-repository
  TAG: latest # ${{ github.event.release.tag_name }}
  PROJECT_ID: dtu-mlops-447711
  GAR_LOCATION: europe-docker.pkg.dev/dtu-mlops-447711/default-container-repository/

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Set up GCP_SA_KEY_DVC
        env:
          GCP_SA_KEY_DVC: ${{ secrets.GCP_SA_KEY_DVC }}
        run: echo "Setting up GCP_SA_KEY_DVC"

      - name: Setup GCP SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker authentication
        run: |
          gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev --quiet

      - name: Build images
        env:
          GCP_SA_KEY_DVC: ${{ secrets.GCP_SA_KEY_DVC }}
        run: |
          for dockerfile in dockerfiles/*.dockerfile; do
            image_name=$(basename $dockerfile .dockerfile)
            docker build --secret id=GCP_SA_KEY_DVC -f $dockerfile . -t ${{ env.GAR_LOCATION }}$image_name:${{ env.TAG }} &
          done
          wait

      - name: Upload to Artifact Registry
        run: |
          for dockerfile in dockerfiles/*.dockerfile; do
            image_name=$(basename $dockerfile .dockerfile)
            docker push ${{ env.GAR_LOCATION }}$image_name:${{ env.TAG }} &
          done
          wait

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app --image ${{ env.GAR_LOCATION }}api:${{ env.TAG }} --platform managed --region europe-west4 --allow-unauthenticated &
          gcloud run deploy streamlit-app --image ${{ env.GAR_LOCATION }}frontend:${{ env.TAG }} --platform managed --region europe-west4 --allow-unauthenticated --set-env-vars BACKEND="https://fastapi-app-840739092468.europe-west4.run.app" &
          wait
