name: Run a locust load test on the API testing instance

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"

jobs:
  testrunner:
    name: "Run a locust load test suite"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: dtu_mlops_project
          python-version: 3.12 
          channels: conda-forge

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Extract deployed model URL
        run: |
          DEPLOYED_MODEL_URL=$(gcloud run services describe fastapi-app-test \
          --region=europe-west4 \
          --format='value(status.url)')
          echo "DEPLOYED_MODEL_URL=$DEPLOYED_MODEL_URL" >> $GITHUB_ENV

      - name: Run the load tests
        run: |
          locust -f tests/performancetests/locustfile.py \
            --headless -u 100 -r 10 --run-time 10m --host=$DEPLOYED_MODEL_URL --csv=/locust/results

      - name: Upload locust results
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: /locust
