name: Run the test suite with pytest

on:
  push:
    path:
      - '**.py'

jobs:
  format:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12 

      - name: Create conda environment
        run: |
          pip install invoke
          invoke create-environment
          conda init

      - name: Install dependencies
        run: |
          conda activate dtu_mlops_project
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run the tests
        run: |
          invoke test
          coverage report
